"""fixed

Revision ID: 8a334315d01f
Revises: 702f89ef4f8d
Create Date: 2022-08-29 11:28:30.919227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a334315d01f'
down_revision = '702f89ef4f8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
