"""fixed

Revision ID: 9dc7a151d680
Revises: 23a57716b5b8
Create Date: 2022-08-29 11:35:52.817241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc7a151d680'
down_revision = '23a57716b5b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
