"""fixed

Revision ID: c1b25c4e8ad2
Revises: 9dc7a151d680
Create Date: 2022-08-29 11:39:17.184496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b25c4e8ad2'
down_revision = '9dc7a151d680'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
